
set(FILES
    Include/Javascript/JavascriptBus.h
    Include/JavascriptComponent.h
    Include/JavascriptContext.h
    Include/JavascriptVariant.h
    Include/JavascriptTypes.h
    Include/JavascriptProperty.h
    Include/JavascriptInstance.h
    Include/Utils/DuktapeUtils.h
    Include/Utils/JavascriptUtils.h
    Source/JavascriptModuleInterface.h
    Source/JavascriptSystemComponent.cpp
    Source/JavascriptSystemComponent.h
    Source/JavascriptComponent.cpp
    Source/JavascriptContext.cpp
    Source/JavascriptVariant.cpp
    Source/JavascriptProperty.cpp
    Source/JavascriptInstance.cpp
    Source/Utils/DuktapeUtils.cpp
    Source/Utils/JavascriptUtils.cpp
)
